// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDirectory(arg1, arg2) {
  return window['go']['guiapp']['App']['BrowseDirectory'](arg1, arg2);
}

export function BrowseFile() {
  return window['go']['guiapp']['App']['BrowseFile']();
}

export function BrowseFolder() {
  return window['go']['guiapp']['App']['BrowseFolder']();
}

export function BrowsePath() {
  return window['go']['guiapp']['App']['BrowsePath']();
}

export function CancelDupeCheck(arg1) {
  return window['go']['guiapp']['App']['CancelDupeCheck'](arg1);
}

export function CancelTrackerUpload(arg1) {
  return window['go']['guiapp']['App']['CancelTrackerUpload'](arg1);
}

export function CheckDupes(arg1, arg2, arg3, arg4) {
  return window['go']['guiapp']['App']['CheckDupes'](arg1, arg2, arg3, arg4);
}

export function CreateWebAuth(arg1, arg2) {
  return window['go']['guiapp']['App']['CreateWebAuth'](arg1, arg2);
}

export function DeleteHistoryRelease(arg1) {
  return window['go']['guiapp']['App']['DeleteHistoryRelease'](arg1);
}

export function DeleteScreenshot(arg1, arg2, arg3, arg4) {
  return window['go']['guiapp']['App']['DeleteScreenshot'](arg1, arg2, arg3, arg4);
}

export function DeleteTrackerImageURL(arg1, arg2, arg3, arg4) {
  return window['go']['guiapp']['App']['DeleteTrackerImageURL'](arg1, arg2, arg3, arg4);
}

export function DeleteUploadedImage(arg1, arg2, arg3) {
  return window['go']['guiapp']['App']['DeleteUploadedImage'](arg1, arg2, arg3);
}

export function DetectDiscType(arg1) {
  return window['go']['guiapp']['App']['DetectDiscType'](arg1);
}

export function DiscoverPlaylists(arg1) {
  return window['go']['guiapp']['App']['DiscoverPlaylists'](arg1);
}

export function ExportConfig() {
  return window['go']['guiapp']['App']['ExportConfig']();
}

export function FetchDescriptionBuilder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['guiapp']['App']['FetchDescriptionBuilder'](arg1, arg2, arg3, arg4, arg5);
}

export function FetchMetadata(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['guiapp']['App']['FetchMetadata'](arg1, arg2, arg3, arg4, arg5);
}

export function FetchPreparation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['guiapp']['App']['FetchPreparation'](arg1, arg2, arg3, arg4, arg5);
}

export function FetchScreenshotPlan(arg1, arg2, arg3) {
  return window['go']['guiapp']['App']['FetchScreenshotPlan'](arg1, arg2, arg3);
}

export function FetchTrackerDryRun(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['guiapp']['App']['FetchTrackerDryRun'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function GenerateScreenshots(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['guiapp']['App']['GenerateScreenshots'](arg1, arg2, arg3, arg4, arg5);
}

export function GetConfig() {
  return window['go']['guiapp']['App']['GetConfig']();
}

export function GetDefaultConfig() {
  return window['go']['guiapp']['App']['GetDefaultConfig']();
}

export function GetDupeCheckSnapshot(arg1) {
  return window['go']['guiapp']['App']['GetDupeCheckSnapshot'](arg1);
}

export function GetHistoryOverview(arg1) {
  return window['go']['guiapp']['App']['GetHistoryOverview'](arg1);
}

export function GetImageHostPolicyMetadata() {
  return window['go']['guiapp']['App']['GetImageHostPolicyMetadata']();
}

export function GetLogExclusions() {
  return window['go']['guiapp']['App']['GetLogExclusions']();
}

export function GetLogPath() {
  return window['go']['guiapp']['App']['GetLogPath']();
}

export function GetRecentLogs(arg1) {
  return window['go']['guiapp']['App']['GetRecentLogs'](arg1);
}

export function GetTrackerUploadSnapshot(arg1) {
  return window['go']['guiapp']['App']['GetTrackerUploadSnapshot'](arg1);
}

export function GetUIState(arg1) {
  return window['go']['guiapp']['App']['GetUIState'](arg1);
}

export function GetWebAuthStatus() {
  return window['go']['guiapp']['App']['GetWebAuthStatus']();
}

export function ImportConfig() {
  return window['go']['guiapp']['App']['ImportConfig']();
}

export function ListHistory() {
  return window['go']['guiapp']['App']['ListHistory']();
}

export function ListKnownTrackers() {
  return window['go']['guiapp']['App']['ListKnownTrackers']();
}

export function ListUIStates() {
  return window['go']['guiapp']['App']['ListUIStates']();
}

export function ListUploadCandidates(arg1, arg2, arg3) {
  return window['go']['guiapp']['App']['ListUploadCandidates'](arg1, arg2, arg3);
}

export function ListUploadedImages(arg1, arg2, arg3) {
  return window['go']['guiapp']['App']['ListUploadedImages'](arg1, arg2, arg3);
}

export function LoadPlaylistSelection(arg1) {
  return window['go']['guiapp']['App']['LoadPlaylistSelection'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['guiapp']['App']['OpenExternalURL'](arg1);
}

export function PreviewScreenshotFrame(arg1, arg2, arg3, arg4) {
  return window['go']['guiapp']['App']['PreviewScreenshotFrame'](arg1, arg2, arg3, arg4);
}

export function ReadScreenshotImage(arg1) {
  return window['go']['guiapp']['App']['ReadScreenshotImage'](arg1);
}

export function RenderDescription(arg1) {
  return window['go']['guiapp']['App']['RenderDescription'](arg1);
}

export function ResetMetadata(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['guiapp']['App']['ResetMetadata'](arg1, arg2, arg3, arg4, arg5);
}

export function RetryFailedTrackerUpload(arg1) {
  return window['go']['guiapp']['App']['RetryFailedTrackerUpload'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['guiapp']['App']['SaveConfig'](arg1);
}

export function SaveDescriptionOverride(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['guiapp']['App']['SaveDescriptionOverride'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveFinalScreenshotSelections(arg1, arg2, arg3, arg4) {
  return window['go']['guiapp']['App']['SaveFinalScreenshotSelections'](arg1, arg2, arg3, arg4);
}

export function SavePlaylistSelection(arg1, arg2, arg3) {
  return window['go']['guiapp']['App']['SavePlaylistSelection'](arg1, arg2, arg3);
}

export function SaveUIState(arg1, arg2, arg3) {
  return window['go']['guiapp']['App']['SaveUIState'](arg1, arg2, arg3);
}

export function StartDupeCheck(arg1, arg2, arg3, arg4) {
  return window['go']['guiapp']['App']['StartDupeCheck'](arg1, arg2, arg3, arg4);
}

export function StartLogStream() {
  return window['go']['guiapp']['App']['StartLogStream']();
}

export function StartTrackerUpload(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['guiapp']['App']['StartTrackerUpload'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function StopLogStream(arg1) {
  return window['go']['guiapp']['App']['StopLogStream'](arg1);
}

export function UpdateLogExclusions(arg1) {
  return window['go']['guiapp']['App']['UpdateLogExclusions'](arg1);
}

export function UploadImages(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['guiapp']['App']['UploadImages'](arg1, arg2, arg3, arg4, arg5, arg6);
}
