// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {guiapp} from '../models';
import {logging} from '../models';

export function BrowseDirectory(arg1:string,arg2:string):Promise<api.BrowseDirectoryResponse>;

export function BrowseFile():Promise<string>;

export function BrowseFolder():Promise<string>;

export function BrowsePath():Promise<string>;

export function CancelDupeCheck(arg1:string):Promise<void>;

export function CancelTrackerUpload(arg1:string):Promise<void>;

export function CheckDupes(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<string>):Promise<api.DupeCheckSummary>;

export function CreateWebAuth(arg1:string,arg2:string):Promise<guiapp.WebAuthStatus>;

export function DeleteHistoryRelease(arg1:string):Promise<void>;

export function DeleteScreenshot(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:string):Promise<void>;

export function DeleteTrackerImageURL(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:string):Promise<void>;

export function DeleteUploadedImage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DetectDiscType(arg1:string):Promise<string>;

export function DiscoverPlaylists(arg1:string):Promise<Array<api.PlaylistInfo>>;

export function ExportConfig():Promise<string>;

export function FetchDescriptionBuilder(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<string>,arg5:Array<string>):Promise<api.DescriptionBuilderPreview>;

export function FetchMetadata(arg1:string,arg2:string,arg3:api.ExternalIDOverrides,arg4:api.ReleaseNameOverrides,arg5:Array<string>):Promise<api.MetadataPreview>;

export function FetchPreparation(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<string>,arg5:Array<string>):Promise<api.PreparationPreview>;

export function FetchScreenshotPlan(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides):Promise<api.ScreenshotPlan>;

export function FetchTrackerDryRun(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<string>,arg5:boolean,arg6:Array<string>,arg7:Record<string, Record<string, string>>,arg8:Array<api.DescriptionBuilderGroup>,arg9:boolean,arg10:string):Promise<api.TrackerDryRunPreview>;

export function GenerateScreenshots(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<api.ScreenshotSelection>,arg5:api.ScreenshotPurpose):Promise<api.ScreenshotResult>;

export function GetConfig():Promise<string>;

export function GetDefaultConfig():Promise<string>;

export function GetDupeCheckSnapshot(arg1:string):Promise<guiapp.DupeCheckSnapshot>;

export function GetHistoryOverview(arg1:string):Promise<api.HistoryOverview>;

export function GetImageHostPolicyMetadata():Promise<any>;

export function GetLogExclusions():Promise<Array<string>>;

export function GetLogPath():Promise<string>;

export function GetRecentLogs(arg1:number):Promise<Array<logging.Entry>>;

export function GetTrackerUploadSnapshot(arg1:string):Promise<guiapp.TrackerUploadSnapshot>;

export function GetUIState(arg1:string):Promise<api.UIStateRecord>;

export function GetWebAuthStatus():Promise<guiapp.WebAuthStatus>;

export function ImportConfig():Promise<guiapp.ImportResult>;

export function ListHistory():Promise<Array<api.HistoryEntry>>;

export function ListKnownTrackers():Promise<Array<string>>;

export function ListUIStates():Promise<api.UIStateList>;

export function ListUploadCandidates(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides):Promise<Array<api.ScreenshotImage>>;

export function ListUploadedImages(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides):Promise<Array<api.UploadedImageLink>>;

export function LoadPlaylistSelection(arg1:string):Promise<api.PlaylistSelection>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function PreviewScreenshotFrame(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:number):Promise<string>;

export function ReadScreenshotImage(arg1:string):Promise<string>;

export function RenderDescription(arg1:string):Promise<string>;

export function ResetMetadata(arg1:string,arg2:string,arg3:api.ExternalIDOverrides,arg4:api.ReleaseNameOverrides,arg5:Array<string>):Promise<api.MetadataPreview>;

export function RetryFailedTrackerUpload(arg1:string):Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function SaveDescriptionOverride(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:api.ExternalIDOverrides,arg6:api.ReleaseNameOverrides):Promise<api.DescriptionBuilderGroup>;

export function SaveFinalScreenshotSelections(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<api.ScreenshotImage>):Promise<void>;

export function SavePlaylistSelection(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SaveUIState(arg1:string,arg2:string,arg3:api.UIState):Promise<void>;

export function StartDupeCheck(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<string>):Promise<string>;

export function StartLogStream():Promise<string>;

export function StartTrackerUpload(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<string>,arg5:boolean,arg6:Array<string>,arg7:Record<string, Record<string, string>>,arg8:Array<api.DescriptionBuilderGroup>,arg9:boolean,arg10:string):Promise<string>;

export function StopLogStream(arg1:string):Promise<void>;

export function UpdateLogExclusions(arg1:Array<string>):Promise<void>;

export function UploadImages(arg1:string,arg2:api.ExternalIDOverrides,arg3:api.ReleaseNameOverrides,arg4:Array<string>,arg5:string,arg6:Array<api.ScreenshotImage>):Promise<api.UploadImagesResult>;
