// Copyright (c) 2025-2026, Audionut and the autobrr contributors.
// SPDX-License-Identifier: GPL-2.0-or-later

package metadata

// serviceCodeMap maps filename/NFO service aliases to the normalized service
// token used in generated release names.
func serviceCodeMap() map[string]string {
	return map[string]string{
		"3SAT":                             "3SAT",
		"3Sat":                             "3SAT",
		"9NOW":                             "9NOW",
		"9Now":                             "9NOW",
		"AND":                              "AND",
		"Animation Digital Network":        "AND",
		"AE":                               "AE",
		"A&E":                              "AE",
		"AJAZ":                             "AJAZ",
		"Al Jazeera English":               "AJAZ",
		"ALL4":                             "ALL4",
		"Channel 4":                        "ALL4",
		"AMBC":                             "AMBC",
		"ABC":                              "AMBC",
		"AMC":                              "AMC",
		"AMZN":                             "AMZN",
		"Amazon":                           "AMZN",
		"AMAZON":                           "AMZN",
		"Amazon Prime":                     "AMZN",
		"ANLB":                             "ANLB",
		"AnimeLab":                         "ANLB",
		"ANPL":                             "ANPL",
		"Animal Planet":                    "ANPL",
		"AOL":                              "AOL",
		"ARD":                              "ARD",
		"ARD Mediathek":                    "ARD",
		"ARDP":                             "ARDP",
		"ARD Plus":                         "ARDP",
		"ARTE":                             "ARTE",
		"AS":                               "AS",
		"Adult Swim":                       "AS",
		"ATK":                              "ATK",
		"America's Test Kitchen":           "ATK",
		"ATV":                              "ATV",
		"Apple TV":                         "ATV",
		"ATVP":                             "ATVP",
		"Apple TV+":                        "ATVP",
		"AUBC":                             "AUBC",
		"ABC Australia":                    "AUBC",
		"BCORE":                            "BCORE",
		"Bilibili":                         "BILI",
		"BILI":                             "BILI",
		"BKPL":                             "BKPL",
		"Blackpills":                       "BKPL",
		"BluTV":                            "BLU",
		"Binge":                            "BNGE",
		"BOOM":                             "BOOM",
		"Boomerang":                        "BOOM",
		"Brasil Paralelo":                  "BP",
		"BP":                               "BP",
		"BRAV":                             "BRAV",
		"BravoTV":                          "BRAV",
		"CBC":                              "CBC",
		"CBS":                              "CBS",
		"CC":                               "CC",
		"Comedy Central":                   "CC",
		"CCGC":                             "CCGC",
		"Comedians in Cars Getting Coffee": "CCGC",
		"CHGD":                             "CHGD",
		"CHRGD":                            "CHGD",
		"CMAX":                             "CMAX",
		"Cinemax":                          "CMAX",
		"CMOR":                             "CMOR",
		"CMT":                              "CMT",
		"Country Music Television":         "CMT",
		"CN":                               "CN",
		"Cartoon Network":                  "CN",
		"CNBC":                             "CNBC",
		"CNLP":                             "CNLP",
		"Canal+":                           "CNLP",
		"CNGO":                             "CNGO",
		"Cinego":                           "CNGO",
		"COOK":                             "COOK",
		"CORE":                             "CORE",
		"CR":                               "CR",
		"Crunchy Roll":                     "CR",
		"Crave":                            "CRAV",
		"CRAV":                             "CRAV",
		"CRIT":                             "CRIT",
		"Criterion":                        "CRIT",
		"Chorki":                           "CRKI",
		"CRKI":                             "CRKI",
		"CRKL":                             "CRKL",
		"Crackle":                          "CRKL",
		"CSPN":                             "CSPN",
		"CSpan":                            "CSPN",
		"CTHP":                             "CTHP",
		"CTV":                              "CTV",
		"CUR":                              "CUR",
		"CuriosityStream":                  "CUR",
		"CW":                               "CW",
		"The CW":                           "CW",
		"CWS":                              "CWS",
		"CWSeed":                           "CWS",
		"DARKROOM":                         "DARKROOM",
		"DAZN":                             "DAZN",
		"DCU":                              "DCU",
		"DC Universe":                      "DCU",
		"DDY":                              "DDY",
		"Digiturk Diledigin Yerde":         "DDY",
		"DEST":                             "DEST",
		"DramaFever":                       "DF",
		"DHF":                              "DHF",
		"Deadhouse Films":                  "DHF",
		"DISC":                             "DISC",
		"Discovery":                        "DISC",
		"DIY":                              "DIY",
		"DIY Network":                      "DIY",
		"DOCC":                             "DOCC",
		"Doc Club":                         "DOCC",
		"DOCPLAY":                          "DOCPLAY",
		"DPLY":                             "DPLY",
		"DPlay":                            "DPLY",
		"DRPO":                             "DRPO",
		"Discovery Plus":                   "DSCP",
		"DSKI":                             "DSKI",
		"Daisuki":                          "DSKI",
		"DSNP":                             "DSNP",
		"Disney+":                          "DSNP",
		"DSNY":                             "DSNY",
		"Disney":                           "DSNY",
		"DTV":                              "DTV",
		"EPIX":                             "EPIX",
		"ePix":                             "EPIX",
		"ESPN":                             "ESPN",
		"ESQ":                              "ESQ",
		"Esquire":                          "ESQ",
		"ETTV":                             "ETTV",
		"El Trece":                         "ETTV",
		"ETV":                              "ETV",
		"E!":                               "ETV",
		"FAM":                              "FAM",
		"Fandor":                           "FANDOR",
		"Facebook Watch":                   "FBWatch",
		"FJR":                              "FJR",
		"Family Jr":                        "FJR",
		"FMIO":                             "FMIO",
		"Filmio":                           "FMIO",
		"FOOD":                             "FOOD",
		"Food Network":                     "FOOD",
		"FOX":                              "FOX",
		"Fox":                              "FOX",
		"Fox Premium":                      "FOXP",
		"UFC Fight Pass":                   "FP",
		"FPT":                              "FPT",
		"FREE":                             "FREE",
		"Freeform":                         "FREE",
		"FTV":                              "FTV",
		"FUNI":                             "FUNI",
		"FUNi":                             "FUNI",
		"Foxtel":                           "FXTL",
		"FYI":                              "FYI",
		"FYI Network":                      "FYI",
		"GC":                               "GC",
		"NHL GameCenter":                   "GC",
		"GLBL":                             "GLBL",
		"Global":                           "GLBL",
		"GLBO":                             "GLBO",
		"Globoplay":                        "GLBO",
		"GLOB":                             "GLOB",
		"GloboSat Play":                    "GLOB",
		"GO90":                             "GO90",
		"GagaOOLala":                       "Gaga",
		"HBO":                              "HBO",
		"HBO Go":                           "HBO",
		"HGTV":                             "HGTV",
		"HIDI":                             "HIDI",
		"HiDive":                           "HIDI",
		"HIST":                             "HIST",
		"History":                          "HIST",
		"HLMK":                             "HLMK",
		"Hallmark":                         "HLMK",
		"HMAX":                             "HMAX",
		"HBO Max":                          "HMAX",
		"HBOMAX":                           "HMAX",
		"HS":                               "HTSR",
		"HTSR":                             "HTSR",
		"HSTR":                             "Hotstar",
		"HULU":                             "HULU",
		"Hulu":                             "HULU",
		"hoichoi":                          "HoiChoi",
		"ID":                               "ID",
		"Investigation Discovery":          "ID",
		"IFC":                              "IFC",
		"iflix":                            "IFX",
		"National Audiovisual Institute":   "INA",
		"ITV":                              "ITV",
		"JOYN":                             "JOYN",
		"KAYO":                             "KAYO",
		"KiKA":                             "KiKA",
		"KNOW":                             "KNOW",
		"Knowledge Network":                "KNOW",
		"KNPY":                             "KNPY",
		"Kanopy":                           "KNPY",
		"Kocowa+":                          "KCW",
		"Kocowa":                           "KCW",
		"KCW":                              "KCW",
		"LIFE":                             "LIFE",
		"Lifetime":                         "LIFE",
		"LN":                               "LN",
		"MA":                               "MA",
		"Looke":                            "LOOKE",
		"LOOKE":                            "LOOKE",
		"Movies Anywhere":                  "MA",
		"MAX":                              "MAX",
		"MBC":                              "MBC",
		"MNBC":                             "MNBC",
		"MSNBC":                            "MNBC",
		"MGMP":                             "MGMP",
		"MGM+":                             "MGMP",
		"MGM Plus":                         "MGMP",
		"MGMPlus":                          "MGMP",
		"MTOD":                             "MTOD",
		"Motor Trend OnDemand":             "MTOD",
		"MTV":                              "MTV",
		"MUBI":                             "MUBI",
		"NATG":                             "NATG",
		"National Geographic":              "NATG",
		"NBA":                              "NBA",
		"NBA TV":                           "NBA",
		"NBC":                              "NBC",
		"NF":                               "NF",
		"NBLA":                             "NBLA",
		"Nebula":                           "NBLA",
		"Netflix":                          "NF",
		"National Film Board":              "NFB",
		"NFL":                              "NFL",
		"NFLN":                             "NFLN",
		"NFL Now":                          "NFLN",
		"NICK":                             "NICK",
		"Nickelodeon":                      "NICK",
		"NOW":                              "NOW",
		"NOWTV":                            "NOW",
		"NRK":                              "NRK",
		"Norsk Rikskringkasting":           "NRK",
		"OnDemandKorea":                    "ODK",
		"Opto":                             "OPTO",
		"ORF":                              "ORF",
		"ORF ON":                           "ORF",
		"Oprah Winfrey Network":            "OWN",
		"PA":                               "PA",
		"PBS":                              "PBS",
		"PBSK":                             "PBSK",
		"PBS Kids":                         "PBSK",
		"PCOK":                             "PCOK",
		"Peacock":                          "PCOK",
		"PLAY":                             "PLAY",
		"PLTV":                             "PLTV",
		"Pluto TV":                         "PLTV",
		"PLUZ":                             "PLUZ",
		"Pluzz":                            "PLUZ",
		"PMNP":                             "PMNP",
		"PMNT":                             "PMNT",
		"PMTP":                             "PMTP",
		"POGO":                             "POGO",
		"PokerGO":                          "POGO",
		"PSN":                              "PSN",
		"Playstation Network":              "PSN",
		"PUHU":                             "PUHU",
		"QIBI":                             "QIBI",
		"RED":                              "RED",
		"YouTube Red":                      "RED",
		"RKTN":                             "RKTN",
		"Rakuten TV":                       "RKTN",
		"The Roku Channel":                 "ROKU",
		"RNET":                             "RNET",
		"OBB Railnet":                      "RNET",
		"RSTR":                             "RSTR",
		"RTE":                              "RTE",
		"RTE One":                          "RTE",
		"RTLP":                             "RTLP",
		"RTL+":                             "RTLP",
		"RUUTU":                            "RUUTU",
		"SBS":                              "SBS",
		"Science Channel":                  "SCI",
		"SESO":                             "SESO",
		"SeeSo":                            "SESO",
		"SHMI":                             "SHMI",
		"Shomi":                            "SHMI",
		"SKST":                             "SKST",
		"SkyShowtime":                      "SKST",
		"SHO":                              "SHO",
		"Showtime":                         "SHO",
		"SNET":                             "SNET",
		"Sportsnet":                        "SNET",
		"Sony":                             "SONY",
		"SPIK":                             "SPIK",
		"Spike":                            "SPIK",
		"Spike TV":                         "SPKE",
		"SPRT":                             "SPRT",
		"Sprout":                           "SPRT",
		"STAN":                             "STAN",
		"Stan":                             "STAN",
		"STARZ":                            "STARZ",
		"STRP":                             "STRP",
		"Star+":                            "STRP",
		"STZ":                              "STZ",
		"Starz":                            "STZ",
		"SVT":                              "SVT",
		"Sveriges Television":              "SVT",
		"SWER":                             "SWER",
		"SwearNet":                         "SWER",
		"SYFY":                             "SYFY",
		"Syfy":                             "SYFY",
		"TBS":                              "TBS",
		"TEN":                              "TEN",
		"TIMV":                             "TIMV",
		"TIMvision":                        "TIMV",
		"TFOU":                             "TFOU",
		"TFou":                             "TFOU",
		"TLC":                              "TLC",
		"TOU":                              "TOU",
		"TRVL":                             "TRVL",
		"TUBI":                             "TUBI",
		"TubiTV":                           "TUBI",
		"TV3":                              "TV3",
		"TV3 Ireland":                      "TV3",
		"TV4":                              "TV4",
		"TV4 Sweeden":                      "TV4",
		"TVING":                            "TVING",
		"TVL":                              "TVL",
		"TV Land":                          "TVL",
		"TVNZ":                             "TVNZ",
		"UFC":                              "UFC",
		"UKTV":                             "UKTV",
		"UNIV":                             "UNIV",
		"Univision":                        "UNIV",
		"USAN":                             "USAN",
		"USA Network":                      "USAN",
		"VH1":                              "VH1",
		"VIAP":                             "VIAP",
		"VICE":                             "VICE",
		"Viceland":                         "VICE",
		"Viki":                             "VIKI",
		"VIMEO":                            "VIMEO",
		"Vivamax":                          "VMAX",
		"VMAX":                             "VMAX",
		"Vivaone":                          "VONE",
		"VONE":                             "VONE",
		"VLCT":                             "VLCT",
		"Velocity":                         "VLCT",
		"VMEO":                             "VMEO",
		"Vimeo":                            "VMEO",
		"VRV":                              "VRV",
		"VUDU":                             "VUDU",
		"WME":                              "WME",
		"WatchMe":                          "WME",
		"WNET":                             "WNET",
		"W Network":                        "WNET",
		"WOW Presents Plus":                "WOWP",
		"WOWP":                             "WOWP",
		"WWEN":                             "WWEN",
		"WWE Network":                      "WWEN",
		"XBOX":                             "XBOX",
		"Xbox Video":                       "XBOX",
		"XUMO":                             "XUMO",
		"YHOO":                             "YHOO",
		"Yahoo":                            "YHOO",
		"YT":                               "YT",
		"ZDF":                              "ZDF",
		"iP":                               "iP",
		"BBC iPlayer":                      "iP",
		"iQIYI":                            "iQIYI",
		"iT":                               "iT",
		"ITUNES":                           "iT",
		"iTunes":                           "iT",
		"MGG":                              "MGG",
		"Megogo":                           "MGG",
		"MEGOGO":                           "MGG",
		"MeGoGo":                           "MGG",
		"SWEET":                            "SWEET",
		"KS":                               "KS",
		"Kyivstar":                         "KS",
		"KyivstarTV":                       "KS",
		"Kyivstar TV":                      "KS",
		"kyivstar":                         "KS",
		"PKO":                              "PKO",
		"Planeta Kino Online":              "PKO",
		"TF":                               "TF",
		"takflix":                          "TF",
		"Takflix":                          "TF",
	}
}
